### ISSUE TITLE
Something is wonky with the AFQ  tracts profile example

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1985]
This figure looks quite wrong: 

![image](https://user-images.githubusercontent.com/118582/67047177-a1404980-f0e6-11e9-8063-7d18c20f7fc9.png)

**Comment by arokem** [comment]
I'm getting this when running locally on my laptop
![tract_profiles](https://user-images.githubusercontent.com/118582/67047245-cc2a9d80-f0e6-11e9-9481-981fb5a65c26.png)

Which seems about right.

**Comment by skoudoro** [comment]
here what I'm getting on my macOS (python3.7). Different results from both of you...

![tract_profiles](https://user-images.githubusercontent.com/23106443/67048368-62d17b80-f134-11e9-8af8-2a44a211948c.png)

**Comment by arokem** [comment]
Wow. That's a head-scratcher. I'm also on MacOS, with python 3.7. I have a hunch that it might have to do with the state of our examples directory when we start running this, because these results depend on tracking and then on bundle recognition, so there are a bunch of moving pieces upstream from this.

**Comment by arokem** [comment]
Deleting my entire examples directory, getting a fresh checkout of all these files, and then rerunning resulted in the same figure I got before.

**Comment by captainnova** [comment]
My figure looks sort of like skoudoro's for the CST, but more like the tutorial page's for the AF (it is a bit different, though): 
![tract_profiles](https://user-images.githubusercontent.com/15852777/67051816-d4440680-f101-11e9-8973-f75f3729bba8.png)

**Comment by arokem** [comment]
Maybe we should fix the RNG seeds in bundle_extraction?

here:
https://github.com/nipy/dipy/blob/master/doc/examples/bundle_extraction.py#L74

and here:
https://github.com/nipy/dipy/blob/master/doc/examples/bundle_extraction.py#L123

It would be strange if the random element in that script resulted in such
large discrepancies, but it might be useful to check that.

Incoming with a PR.

**Comment by arokem** [comment]
I fixed the random seeds in #1986. Still getting a figure very similar to the one shown above.  

Could you try fetching this down or similarly fixing the seeds and rerunning?

Please make sure to delete the files CST_L.trk, AF_L.trk and slr_transform.npy before running afq_tract_profiles.

**Comment by skoudoro** [comment]
here, what I obtain with your branch (still macOS): 

![tract_profiles](https://user-images.githubusercontent.com/23106443/67056020-b949b480-f14a-11e9-994b-83c3dd89239e.png)

**Comment by arokem** [comment]
Yeah. That looks more like it. I suspect that recobundles sometimes hits a bad starting condition, which could manifest in several different ways (including what we see in our current website build). Merging #1986 would fix it for this case.

**Comment by captainnova** [comment]
I tried deleting CST_L.trk, AF_L.trk and slr_transform.npy, rerunning bundle_extraction with the seeds in #1986, and then afq_tract_profiles, but I still get different tract profiles:
![tract_profiles](https://user-images.githubusercontent.com/15852777/67112711-75cc6600-f19d-11e9-8109-71ba4b95e9b7.png)

I am using CentOS7, so maybe my np.random.RandomState(1984) does not give the same answer as it would on a Mac, but I am concerned by how much the profiles fluctuate with the seed.

I get
In [89]: np.random.RandomState(1984)                                            
Out[89]: RandomState(MT19937) at 0x7F8ECB6FC360
In [90]: len(af_l)                                                              
Out[90]: 137
In [91]: len(recognized_cst_l)                                                  
Out[91]: 1257

**Comment by skoudoro** [comment]
closing in favor of #3175
